# Generated by Django 3.2.7 on 2021-10-09 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 10, 52, 10, 757620, tzinfo=utc), null=True, verbose_name='end date'),
        ),
    ]
